# Generated by Django 5.0.3 on 2024-04-07 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_registration_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
