# Generated by Django 5.0.3 on 2024-04-07 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registration',
        ),
    ]
