# Generated by Django 5.0.3 on 2024-04-08 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_video_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_name',
            field=models.CharField(default='null', max_length=1000),
        ),
    ]
