# Generated by Django 5.0.3 on 2024-04-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_registration_active_registration_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='adminid',
            field=models.CharField(default='Demo', max_length=50),
        ),
        migrations.AddField(
            model_name='payments',
            name='videoid',
            field=models.CharField(default='Demo', max_length=50),
        ),
    ]
