# Generated by Django 5.0.3 on 2024-04-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_payments_adminid_payments_videoid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='username',
        ),
        migrations.AddField(
            model_name='payments',
            name='amount',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
