# Generated by Django 5.0.3 on 2024-04-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_payments_username_payments_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='requests_generated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=10000)),
                ('requesteddate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
